## **Introduction to Numpy**
### Numpy means Numerical Python
Its a general processing array-processing package(used for working with arrays)
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To use Numpy, we first need to import the `numpy`

In [ ]:
import numpy as np

##Arrays
 Numpy array is a grid of values, **all of the same type**.
 Array is the central data structure of the Numpy Library.
 Dimension :

 The number of dimensions is the **rank** of the array; **the shape of an array is a tuple of integers** giving the **size of the array along each dimension**.

**Numpy array attributes**

In Numpy, attributes are properties of arrays that provide information about the array shape,size, datatype, dimension, and so on. There are numerous attributes available, some of these are listed below:

|**Attribute**|**Description**|**Syntax**|
|:---------|:-----------|:------|
|ndim|returns dimension(total number of axes) of the array|arr.ndim|
|T|returns transposed array|arr.T|
|size|returns number of elements in the array|arr.size|
|dtype|returns datatype of elements in the array|arr.dtype|
|shape|returns a tuple of sizes of each dimension|arr.shape|

In [8]:
import numpy as np
arr = np.array([[1,2],[3,4],[1,4]])
arr1 = np.array([[1,2,3,4],[1,2,3,5]])
arr2 = np.array([[[1,2]],[[3,4]]])
print(arr1)
print("arrayshape:",arr1.shape)
print(arr.shape)
print("size:",arr.size)
print(arr.ndim)
print("dimension:",arr2.ndim)
print(arr2)

[[1 2 3 4]
 [1 2 3 5]]
arrayshape: (2, 4)
(3, 2)
size: 6
2
dimension: 3
[[[1 2]]

 [[3 4]]]


In [7]:
arr5 = np.array([[1,2,3],[4,6,3]])
print(arr5.ndim)
print(arr5.dtype)

2
int64


In [10]:
import numpy as np
a = np.array([1, 2, 3,4,9])  # Create a rank 1 array
print("Type:",type(a),
      "\nArray shape:", a.shape,
      "\nArray size:",a.size,
      "\nDatatype:",a.dtype ,
      "\nDimesion:",a.ndim,
      "\nThird element:", a[2])
a[0] = 5                 # Change an element of the array
print("Changed array:",a)

NameError: ignored

## Shape of Array
No. of elements in each dimension

In [ ]:
a1 = np.array([[1, 2],[3,2]])
print("Array shape:",a1.shape)

Array shape: (2, 2)


In [ ]:
a1 = np.array([[1, 2, 4],[3, 2, 5]])
print("Array shape:",a1.shape)

Array shape: (2, 3)


## Reshape of an Array
Reshaping means changing the shape of an array.(Gives a new shape to an array without changing its data)

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension

In [ ]:
import numpy as np
a3 = np.array([1,2,3,4,5,6,7,8])
print(a3.ndim)
# reshape 1D to 2D array
# data_type array_name[x][y];
# x number of Rows , y number of Columns
x = a3.reshape(4,2)
print(x)
print(x.ndim)

1
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


### Reshape from 1D to 3D array
We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

**3D array :**
A Three Dimensional Array or 3D array in C is a collection of two-dimensional arrays

**data_type array_name[x][y][z];**

data_type: Type of data to be stored in each element.

array_name: name of the array

x: Number of 2D arrays.

y: Number of rows in each 2D array.

z: Number of columns in each 2D array.



In [ ]:

a33 =  np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a33.ndim)
print(a33)
arr = a33.reshape(3,2,2)
print(arr)
print(arr.ndim)
# 1D array into 3D array

1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [ ]:
# Reshaping of array
a4 = np.array([1,2,3,4,5,6])
print(a4.ndim)
x1 = a4.reshape(3,2)
#x1 = a4.reshape(2,3)
#x1 = a4.reshape(3,3)
print(x1)
print(x1.ndim)

1
[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
x = np.array([[2,3,2],[3,6,7]])

print(x.ndim)
print(x)
x1 = x.reshape(6,)
print(x1)
print(x1.ndim)

2
[[2 3 2]
 [3 6 7]]
[2 3 2 3 6 7]
1


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print("our array:",b)
print("transposed array:",b.T)
print("shape of array:",b.shape)
print("size of array in axis 0:",b.shape[0],"\nsize of array in axis 1:",b.shape[1])
print(b[0][0], b[0, 1], b[1, 0])

our array: [[1 2 3]
 [4 5 6]]
transposed array: [[1 4]
 [2 5]
 [3 6]]
shape of array: (2, 3)
size of array in axis 0: 2 
size of array in axis 1: 3
1 2 4


### Array creation(initialization)
We can initialize numpy arrays as follows:
+ using List(or tuple)
+ using numpy functions
  + np.arange
  + np.linspace
  + np.zeros
  + np.ones
  + np.full
  + np.eye
  + np.random.random
  + np.empty(np.empty_like)
  
+ using input function


In [ ]:
#array creation using list(tuple)

list_arr=[1,2,3]
#tuple_arr=(5,6,7)
a = np.array(list_arr,dtype=float)  # Create a rank 1 array
print("a array:",a,"shape of array:",a.shape)
b= np.array([[1,2,3],[4,5,6]],dtype=float)  # Create a rank 2 array
print("b array:",b,"shape of array:",b.shape)
c= np.array([[[1,2,3],[4,5,6]],[[2,3,4],[1,1,1]]],dtype=float)  # Create a rank 3 array
print("c array:",c,"shape of array:",c.shape)

d= np.array([[[[1,2],[4,5]]]],dtype=float)  # Create a rank 4 array
print("d array:",d,"shape of array:",d.shape)

a array: [1. 2. 3.] shape of array: (3,)
b array: [[1. 2. 3.]
 [4. 5. 6.]] shape of array: (2, 3)
c array: [[[1. 2. 3.]
  [4. 5. 6.]]

 [[2. 3. 4.]
  [1. 1. 1.]]] shape of array: (2, 2, 3)
d array: [[[[1. 2.]
   [4. 5.]]]] shape of array: (1, 1, 2, 2)


## Array creation using Numpy functions
The **numpy. linspace()** function is used to create an array of evenly spaced numbers within a specified range.
The **numpy.linspace()** function uses the following basic syntax:

numpy.linspace(start, stop, num, …)

where:

**start**: The starting value of the sequence
**stop**: The end value of the sequence
**num**: the number of values to generate

In [ ]:
#using linspace function
#linspace(start, stop, no of sample points)

b=np.linspace(0,10,6)
print(b)


[ 0.  2.  4.  6.  8. 10.]


np.linspace allows you to define how many values you get including the specified min and max value. It infers the stepsize:


In [ ]:
#create sequence of 11 evenly spaced values between 0 and 20
np.linspace(0,20,11)


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

The **np.arange()** function uses the following basic syntax:

np.arange(start, stop, step, …)

where:

**start**: The starting value of the sequence
**stop**: The end value of the sequence
**step**: The spacing between values

**np.arange** excludes the maximum value unless rounding error makes it do otherwise

In [ ]:
#create sequence of values between 0 and 20 where spacing is 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#using arrange function
#arrange(start, stop, step size)

np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
# Create an array of all zeros
a = np.zeros((2,2))
b = np.zeros((3,2),dtype='uint8')  # Create an array of all zeros having data type uint8(unsigned int)
c = np.zeros((2,2),dtype='float')  # Create an array of all zeros
print(a,'\n',b,'\n',c)

[[0. 0.]
 [0. 0.]] 
 [[0 0]
 [0 0]
 [0 0]] 
 [[0. 0.]
 [0. 0.]]


In [ ]:
# Create an array of all ones
b = np.ones((1,2))
c=np.pi*np.ones((1,2))   # Create an array of all pi
print(b)
print(c)

[[1. 1.]]
[[23. 23.]]


In [ ]:
# Create a constant array using full
#full(shape, fill_value, dtype=)
c = np.full((3,2), 90,dtype=float)
#c = np.full((2,2),50,dtype=int)
print(c)

[[90. 90.]
 [90. 90.]
 [90. 90.]]


## numpy.eye
**numpy.eye(N, M=None, k=0, dtype=<class 'float')**

Return a 2-D array with ones on the diagonal and zeros elsewhere

N: int
Number of rows in the output.

M: int, optional
Number of columns in the output. If None, defaults to N.

k: int, optional
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

dtype:data-type, optional
Data-type of the returned array.


In [ ]:
# Create a 2x2 identity matrix
#eye(rows, columns, k=0, dtype)
# main diagonal
a=np.eye(2,2,0)
print("Diagonal matrix:\n",a)
# upper diagonal
a1=np.eye(2,2,1)
print("Upper diagonal matrix:\n",a1)
# lower diagonal
a2=np.eye(2,2,-1)
print("Lower Diagonal matrix:\n",a2)

d=2*np.eye(4,4,-1)+3*np.eye(4,4,1)
print("4x4 matrix with diagonal entries zeros:\n",d)

Diagonal matrix:
 [[1. 0.]
 [0. 1.]]
Upper diagonal matrix:
 [[0. 1.]
 [0. 0.]]
Lower Diagonal matrix:
 [[0. 0.]
 [1. 0.]]
4x4 matrix with diagonal entries zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d=2*np.eye(4,4,-1)+3*np.eye(4,4,1)+4*np.eye(4,4,0)
print("4x4 matrix with diagonal entries zeros:\n",d)

4x4 matrix with diagonal entries zeros:
 [[4. 3. 0. 0.]
 [2. 4. 3. 0.]
 [0. 2. 4. 3.]
 [0. 0. 2. 4.]]


**Array of Random values**

An array with random values
Return random floats in the half-open interval [0.0, 1.0).

In [ ]:
# Create an array filled with random values
e = np.random.random((2,3))
print(e)

[[0.98810101 0.80151993 0.50472034]
 [0.13131218 0.58596835 0.68871771]]


##Split()
Splitting is reverse operation of Joining.
Joining merges multiple arrays into one and Splitting breaks one array into multiple

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


The **map() function** in NumPy takes the two parameters function-name and iterable.
The function name is the name of the particular function that must be applied on each value in the given list of values or the iterable.
Iterable is the list of values on which the particular function by name function must be applied.
The map() function in numpy returns a list of values on which the specified function is applied.

In [ ]:
#please add map function in lecture 1. its very important function
def my_func(x,y):
    return x+y
z=map(my_func,(2,3),(3,4))
print(list(z)) #?

[5, 7]


## Functions in Numpy
Some of the functions are as follows
reshape()
flatten()
reval()
trace()
transpose()

In [ ]:
# how to use reshape function
a=np.arange(0,10,1)
print(a)
b=a.reshape(2,5)
print(b)
# in one line
a=np.arange(10).reshape(2,5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


**flatten( ) :**

returns a copy of array collapsed in one dimension


In [ ]:
a=np.arange(10).reshape(2,5)
print(a)
b=a.flatten()
print(b)
b[0]=100
print(b)
# copy of array
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


**ravel( )**

Return a contiguous flattened array.


In [ ]:
# to get a 1 dim array by applying reval function
a=np.arange(10).reshape(2,5)
b=a.ravel()
print(b)
b[0]=100
print(b)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[[100   1   2   3   4]
 [  5   6   7   8   9]]


Ravel is faster than flatten() as it does not occupy any memory.

Flatten() is comparatively slower than ravel() as it occupies memory.

In [ ]:
# the same thing is done by reshape function
a=np.arange(10).reshape(2,5)
print(a)
print(a.reshape(-1))
#ravel and reshape(-1) are the same

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


## Array indexing
Numpy offers several ways to index arrays

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.arange(1,13).reshape(3,4)
print(a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
c = a[:3, 0:1]
print("slice b:",b)
print("slice c:",c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
slice b: [[2 3]
 [6 7]]
slice c: [[1]
 [5]
 [9]]


A slice of an array is a view into the same data(shallow copy), so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


but on the other hand

In [ ]:
c = a[:2, 1:3].copy() #deep copy
print(c)
c[0, 0] = 125
print("value in a don't change",a)
print('after change\n',c)

[[2 3]
 [6 7]]
value in a don't change [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
after change
 [[125   3]
 [  6   7]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print("Rank 1 view of the second row of a",row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rank 1 view of the second row of a [5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])
# a[0, 0]  # 1
# a[1, 1]  # 4
# a[2, 0]  # 5

# The above example of integer array indexing is equivalent to this:
#print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(np.arange(4), b)
print(a[np.arange(4), b]) # Prints "[ 1  6  7 11]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 1 2 3] [0 2 0 1]
[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


## Data Types
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


### Basic Math operations on Numpy arrays
asic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

# Elementwise sum; both produce the array
print("sum = ",x + y) #operator wise
print(np.add(x, y)) #or as a function

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**Note that** unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(x.dot(y))
print(np.dot(v, w))

[[19 22]
 [43 50]]
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

219
